name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspi_4_bullseye:20220121
        commands: |
          uname -a
          whoami

          # Install Docker
          apt update
          apt install curl -y
          curl -sSL https://get.docker.com | sh
          service docker start
          sleep 10
          service docker status

          docker ps

          # Install Docker Compose
          LATEST_VERSION=$(curl -s https://github.com/docker/compose/releases/latest | grep -o "v[0-9]\.[0-9]*\.[0-9]*")
          curl -L "https://github.com/docker/compose/releases/download/$LATEST_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          # Build AGW docker images
          git clone https://github.com/m-govind/magma.git --depth 1
          cd magma/lte/gateway/docker/
          docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64


