name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        # Install the qemu packages
        sudo apt-get install qemu binfmt-support qemu-user-static

        # This step will execute the registering scripts
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        # Testing the emulation environment
        docker run --rm -t arm64v8/ubuntu uname -m
        
        # Test OpenSearch
        mkdir opensearch_data
        chmod 777 opensearch_data
        docker run --name="opensearch" -d -p 9200:9200 -v "${PWD}/opensearch_data:/usr/share/opensearch/data" -e "discovery.type=single-node" -e "plugins.security.ssl.http.enabled=false" -e "ES_JAVA_OPTS=\"-Xmx4g -Xms4g\"" opensearchproject/opensearch:1.3.7 

        sleep 10

        i=1
        timeout=120
        while ! curl -s 127.0.0.1:9200 >/dev/null; do
          if [[ "$i" -gt "$timeout" ]]; then
            echo "timeout occurred after waiting $timeout seconds"
            docker ps
            docker logs opensearch
            curl 127.0.0.1:9200 -v
            exit 1
          fi
          sleep 1
          echo "waited OpenSearch for $i seconds.."
          ((i++));
        done
        curl 127.0.0.1:9200 -v

